### ISSUE TITLE
里面的第三方库不全

### ISSUE THREAD

**Issue by sebastinaa** [zhh2005757/slambook2_in_Docker#2]
里面的第三方库不全，后来我把高翔官方版的拿过来一起编译，后来出错了。。。

**Comment by zhh2005757** [comment]
具体哪些库不全呢?有些库我这里的和高博提供的版本不一样的。

**Comment by sebastinaa** [comment]
你好，里面的fmt,gflags,octmap, glog，原来高博提供的第三方库是需要git clone --recures ，这里的仓库链接没有了

**Comment by zhh2005757** [comment]
是的哦，我这里直接把所有需要的库都clone下来了，这样保证用我的库的版本编译没问题，高博的是需要单独拉取的，这点是不一样的。您可以直接按照我的仓库里的库进行编译，一般没问题的。

**Comment by Robotislove** [comment]
你好，问题就是：git clone --recursive https://github.com/zhh2005757/slambook2_in_Docker.git 后，上面的fmt,gflags,octmap, glog没有，不知道是哪个版本的

**Comment by zhh2005757** [comment]
> 你好，问题就是：git clone --recursive https://github.com/zhh2005757/slambook2_in_Docker.git 后，上面的fmt,gflags,octmap, glog没有，不知道是哪个版本的

之前那几个库用了gitmodule现在去掉了，已上传缺失的库，感谢指出！

**Comment by sebastinaa** [comment]
谢谢，现在可以跑通了，只是docker 容器通过VNC进不去，我这里，Status 显示unhealthy，我是按照你的主页说明来执行的。

**Comment by sebastinaa** [comment]
> > 你好，问题就是：git clone --recursive https://github.com/zhh2005757/slambook2_in_Docker.git 后，上面的fmt,gflags,octmap, glog没有，不知道是哪个版本的
> 
> 之前那几个库用了gitmodule现在去掉了，已上传缺失的库，感谢指出！

那个VNC访问我这里也是用的5900端口，进不去

**Comment by zhh2005757** [comment]
> 
> 
> 
> > > 你好，问题就是：git clone --recursive https://github.com/zhh2005757/slambook2_in_Docker.git 后，上面的fmt,gflags,octmap, glog没有，不知道是哪个版本的
> > 
> > 之前那几个库用了gitmodule现在去掉了，已上传缺失的库，感谢指出！
> 
> 那个VNC访问我这里也是用的5900端口，进不去

看看端口是否有占用，unhealthy的话打一下日志
